FROM node:17-alpine3.14
WORKDIR /usr/src/app
COPY . .
RUN npm install yarn
RUN yarn install
RUN yarn --production

FROM node:17-alpine3.14
WORKDIR /usr/src/app
# COPY . .
RUN npm install yarn
# RUN yarn
COPY --from=0 /usr/src/app/build ./build
COPY . .
EXPOSE 4000
CMD ["node", "/build/index.js"]
