version: "3.7"

# Our services
services:
  lm-backend:
    container_name: lm-backend
    image: lm-backend
    depends_on:
      - lm-backend-db
    build:
      # Where we find the Dockerfile
      context: ./
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    # env_file: .env
    environment:
      - POSTGRES_HOST=lm-backend-db
      - POSTGRES_USER=josemagne
      - POSTGRES_PASSWORD=josemagne
      - POSTGRES_DB=librimem
    volumes:
      - "./:/app"
      - "./node_modules:/app/node_modules"
    networks:
      - lm-network

  lm-backend-db:
    image: "postgres:13"
    container_name: lm-backend-db
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    env_file: .env
    networks:
      - lm-network

networks:
  lm-network:
    driver: bridge
