version: "3.7"

services:
  nginx:
    container_name: lm-webserver
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


  certbot:
    container_name: lm-cerbot
    image: certbot/certbot
    volumes:
      - ./data/certbo/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot 
    
  #container_name: lm-backend
  #image: lm-backend
  #depends_on:
    #- lm-backend-db
  #build:
    #context: ./
    #dockerfile: Dockerfile.production
  #ports:
    #- "4000:4000"
  #environment:
    #- POSTGRES_HOST=lm-backend-db
    #- POSTGRES_USER=josemagne
    #- POSTGRES_PASSWORD=josemagne
    #- POSTGRES_DB=librimem
    #- NODE_ENV=production
  #networks:
    #- lm-network

  #lm-backend-db:
    #image: "postgres:13"
    #container_name: lm-backend-db
    #volumes:
      #- "./pgdata:/var/lib/postgresql/data"
    #environment:
      #- POSTGRES_HOST=lm-backend-db
      #- POSTGRES_USER=josemagne
      #- POSTGRES_PASSWORD=josemagne
      #- POSTGRES_DB=librimem
    #networks:
      #- lm-network

networks:
  lm-network:
    driver: bridge
